// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAin7R2abnL2NVCBrX7ymNmZNOsNMTqVxA',
    appId: '1:99452607802:web:bb6d8214edbacd26680403',
    messagingSenderId: '99452607802',
    projectId: 'runningmate-b0076',
    authDomain: 'runningmate-b0076.firebaseapp.com',
    storageBucket: 'runningmate-b0076.firebasestorage.app',
    measurementId: 'G-16T1KRWR7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFykbhQON8Y_GN3YpzZhXRoV7oaXOW1M',
    appId: '1:99452607802:android:c666b1d9077746a4680403',
    messagingSenderId: '99452607802',
    projectId: 'runningmate-b0076',
    storageBucket: 'runningmate-b0076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1c75oFRKD_RMGHbL1FRqNjtm1JsF1WSY',
    appId: '1:99452607802:ios:c4f7d4686cd58129680403',
    messagingSenderId: '99452607802',
    projectId: 'runningmate-b0076',
    storageBucket: 'runningmate-b0076.firebasestorage.app',
    iosBundleId: 'com.example.runningMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1c75oFRKD_RMGHbL1FRqNjtm1JsF1WSY',
    appId: '1:99452607802:ios:c4f7d4686cd58129680403',
    messagingSenderId: '99452607802',
    projectId: 'runningmate-b0076',
    storageBucket: 'runningmate-b0076.firebasestorage.app',
    iosBundleId: 'com.example.runningMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAin7R2abnL2NVCBrX7ymNmZNOsNMTqVxA',
    appId: '1:99452607802:web:163a72f846767e48680403',
    messagingSenderId: '99452607802',
    projectId: 'runningmate-b0076',
    authDomain: 'runningmate-b0076.firebaseapp.com',
    storageBucket: 'runningmate-b0076.firebasestorage.app',
    measurementId: 'G-XSE04YTLHN',
  );
}
